package leetcode.strings;

import java.util.HashMap;
import java.util.Map;

/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
 */
public class FindTheDifference {

    public static void main(String[] args) {
        String s = "abc";
        String t = "abcd";
        String s1 = "";
        String t1 = "a";

        System.out.println(findTheDifference(s1, t1));
    }

    public static char findTheDifference(String s, String t) {
        Map<Character, Integer> map = new HashMap<>();

        for (char c : s.toCharArray()) {
            map.put(c, map.getOrDefault(c, 0) + 1);
        }
        for (char c : t.toCharArray()) {
            map.put(c, map.getOrDefault(c, 0) - 1);
        }

        for (Map.Entry<Character, Integer> entry : map.entrySet()) {
            if (entry.getValue() < 0) return entry.getKey();
        }
        return '\0';
    }
}
